device: cpu              
max_words: 300        
story_tone: inspirational
story_gen_model: gpt-4  
image_caption_model: blip
clip_model: openai/clip-vit-base-patch32


clustering:
  method: kmeans
  clusters: 5
